export const uzContent={
    title:"Sarlavha",
    price:"Narxi",
    category:"Bo'limi",
    description:"Ta'rif",
    product:"Mahsulot",
    navbar:"Internet Magazin",
    login:"Tizimga kiring & Ro'yxatdan o'ting",
    content:"Ma'lumot",
    new:"Eng yangi",
    best:"Yaxshi sotilgani",
    old:"Eng eski",
    low:"Arzon",
    high:"Qimmat",
}